version: "3"
networks:
  a_malinovsky_default :
    external: true
services:
   db-test:
    container_name: db-test
    image: postgres
    restart: always
    networks:
      - a_malinovsky_default
    environment:
      POSTGRES_PASSWORD: 121212
      POSTGRES_USER: user
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
#      PGTZ: ${TZ}
#      TZ: ${TZ}
    ports:
      - 0.0.0.0:5496:5432
    volumes:
      - /root/postgres/:/var/lib/postgresql/data/

   adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - a_malinovsky_default
    ports:
      - 8099:8080
